CREATE TABLE PAR_CINES 
(    
  ID SERIAL UNIQUE, 
  CODIGO VARCHAR(6) NOT NULL, 
  NOMBRE VARCHAR(400) NOT NULL, 
  CIF VARCHAR(30) NOT NULL, 
  DIRECCION VARCHAR(500) NOT NULL, 
  COD_MUNICIPIO VARCHAR(400) NOT NULL, 
  NOM_MUNICIPIO VARCHAR(400) NOT NULL, 
  CP VARCHAR(400) NOT NULL, 
  EMPRESA VARCHAR(400) NOT NULL, 
  COD_REGISTRO VARCHAR(400) NOT NULL, 
  TFNO VARCHAR(400) NOT NULL,
  IVA INTEGER NOT NULL 
);

CREATE TABLE PAR_SALAS 
(    
  ID SERIAL UNIQUE, 
  CODIGO VARCHAR(6) NOT NULL, 
  NOMBRE VARCHAR(400) NOT NULL, 
  ASIENTOS INTEGER NOT NULL, 
  ASIENTO_DISC INTEGER NOT NULL, 
  ASIENTO_NORES INTEGER NOT NULL, 
  TIPO VARCHAR(30) NOT NULL, 
  FORMATO VARCHAR(500) NOT NULL, 
  SUBTITULO VARCHAR(400) NOT NULL,
  CINE_ID INTEGER NOT NULL
);

ALTER TABLE PAR_SALAS ADD CONSTRAINT PAR_CINES_PAR_SALAS_FK1 FOREIGN KEY (CINE_ID)
      REFERENCES PAR_CINES (ID);

CREATE TABLE PAR_PLANTAS_SALA 
(    
  ID SERIAL UNIQUE, 
  NOMBRE VARCHAR(400) NOT NULL,
  SALA_ID INTEGER NOT NULL
);

ALTER TABLE PAR_PLANTAS_SALA ADD CONSTRAINT PAR_PLANTAS_SALA_PAR_SALAS_FK1 FOREIGN KEY (SALA_ID)
      REFERENCES PAR_PLANTAS_SALA (ID);
      
-- DATOS PELICULAS

ALTER TABLE PAR_EVENTOS ADD COLUMN EXPEDIENTE VARCHAR(400);
ALTER TABLE PAR_EVENTOS ADD COLUMN COD_DISTRI VARCHAR(400);
ALTER TABLE PAR_EVENTOS ADD COLUMN NOM_DISTRI VARCHAR(400);
ALTER TABLE PAR_EVENTOS ADD COLUMN NACIONALIDAD VARCHAR(400);
ALTER TABLE PAR_EVENTOS ADD COLUMN VO VARCHAR(400);
ALTER TABLE PAR_EVENTOS ADD COLUMN METRAJE VARCHAR(400);

-- DATOS SESIONES

ALTER TABLE PAR_SESIONES ADD COLUMN NOMBRE VARCHAR(400);
ALTER TABLE PAR_SESIONES ADD COLUMN SALA_ID INTEGER;
ALTER TABLE PAR_SESIONES ADD COLUMN FORMATO VARCHAR(400);

ALTER TABLE PAR_SESIONES ADD CONSTRAINT PAR_SESIONES_PAR_SALAS_FK1 FOREIGN KEY (SALA_ID)
      REFERENCES PAR_SALAS (ID);
