-- DATOS EVENTOS

ALTER TABLE PAR_EVENTOS ADD COLUMN SUBTITULOS VARCHAR(400);

-- DATOS SESIONES

ALTER TABLE PAR_SESIONES ADD COLUMN VER_LING VARCHAR(400);
ALTER TABLE PAR_SESIONES ADD COLUMN RSS_ID VARCHAR(400);

