CREATE TABLE PAR_EVENTOS_MULTISESION
(
  ID serial NOT NULL,
  EVENTO_ID INTEGER NOT NULL,
  CONSTRAINT PAR_EVENTOS_MULTISESION_PKEY PRIMARY KEY (ID),
  CONSTRAINT PAR_EVENTOS_MULTISESION_KEY UNIQUE (ID, EVENTO_ID),
  CONSTRAINT PAR_EVENTOS_MULTISESION_PAR_EVENTOS_FK1 FOREIGN KEY (EVENTO_ID)
        REFERENCES PAR_EVENTOS (ID)
)
WITH (
  OIDS=FALSE
);