ALTER TABLE PAR_SESIONES ADD COLUMN ANULADA VARCHAR(400);
INSERT INTO par_version_bbdd (VERSION) VALUES ('2014-10-08.SQL');

ALTER TABLE PAR_SESIONES DROP COLUMN ANULADA;
ALTER TABLE PAR_SESIONES ADD COLUMN ANULADA BOOLEAN DEFAULT FALSE;