CREATE TABLE PAR_ABONOS
(
  ID serial NOT NULL,
  NOMBRE character varying(255) not null,
  PLANTILLA_ID integer not null,
  ANULADO boolean DEFAULT false,
  CONSTRAINT PAR_ABONOS_PKEY PRIMARY KEY (ID),
  CONSTRAINT PAR_ABONOS_PAR_PLANTILLAS_FK1 FOREIGN KEY (PLANTILLA_ID)
        REFERENCES PAR_PLANTILLAS (ID)
)
WITH (
  OIDS=FALSE
);

CREATE TABLE PAR_SESIONES_ABONOS
(
  ID serial NOT NULL,
  SESION_ID integer not null,
  ABONO_ID integer not null,
  CONSTRAINT PAR_SESIONES_ABONOS_PKEY PRIMARY KEY (ID),
  CONSTRAINT PAR_SES_ABONOS_SESIONES_FK1 FOREIGN KEY (SESION_ID)
        REFERENCES PAR_SESIONES (ID) ON DELETE CASCADE,
  CONSTRAINT PAR_SES_ABONOS_ABONOS_FK1 FOREIGN KEY (ABONO_ID)
          REFERENCES PAR_ABONOS (ID)
)
WITH (
  OIDS=FALSE
);

CREATE TABLE PAR_ABONADOS
(
  ID serial NOT NULL,
  ABONO_ID integer not null,
  NOMBRE character varying(255),
  APELLIDOS character varying(255),
  TFNO character varying(255),
  EMAIL character varying(255),
  FECHA timestamp without time zone DEFAULT now(),
  IMPORTE integer,
  DIRECCION character varying(255),
  POBLACION character varying(255),
  CP character varying(255),
  PROVINCIA character varying(255),
  INFO_PERIODICA boolean DEFAULT false,
  ANULADO boolean DEFAULT false,
  ABONADOS character varying(2500),
  CONSTRAINT PAR_ABONADOS_PKEY PRIMARY KEY (ID),
  CONSTRAINT PAR_ABONADOS_ABONOS_FK1 FOREIGN KEY (ABONO_ID)
        REFERENCES PAR_ABONOS (ID)
)
WITH (
  OIDS=FALSE
);

ALTER TABLE PAR_COMPRAS ADD COLUMN ABONADO_ID integer;
ALTER TABLE PAR_COMPRAS ADD CONSTRAINT PAR_COMPRAS_ABONADOS_FK1 FOREIGN KEY (ABONADO_ID) REFERENCES PAR_ABONADOS (ID);

INSERT INTO par_version_bbdd (VERSION) VALUES ('2014-12-17.SQL');