ALTER TABLE PAR_BUTACAS ADD COLUMN ID_ENTRADA INT;
ALTER TABLE PAR_BUTACAS ADD CONSTRAINT par_butacas_id_entrada_key UNIQUE (ID_ENTRADA );
UPDATE PAR_BUTACAS SET ID_ENTRADA = ID;

ALTER TABLE PAR_BUTACAS ALTER COLUMN PRECIO TYPE real;
ALTER TABLE PAR_BUTACAS_BORRADAS ALTER COLUMN PRECIO TYPE real;
ALTER TABLE PAR_COMPRAS ALTER COLUMN IMPORTE TYPE real;
ALTER TABLE PAR_COMPRAS_BORRADAS ALTER COLUMN IMPORTE TYPE real;
ALTER TABLE PAR_PRECIOS_PLANTILLA ALTER COLUMN PRECIO TYPE real;
ALTER TABLE PAR_PRECIOS_PLANTILLA ALTER COLUMN DESCUENTO TYPE real;
ALTER TABLE PAR_PRECIOS_PLANTILLA ALTER COLUMN INVITACION TYPE real;
ALTER TABLE PAR_PRECIOS_SESION ALTER COLUMN PRECIO TYPE real;
ALTER TABLE PAR_PRECIOS_SESION ALTER COLUMN DESCUENTO TYPE real;
ALTER TABLE PAR_PRECIOS_SESION ALTER COLUMN INVITACION TYPE real;

INSERT INTO par_version_bbdd (VERSION) VALUES ('2014-11-07.SQL');
