CREATE TABLE PAR_REPORTS
(
  ID SERIAL UNIQUE,
  SALA_ID INTEGER,
  CLASE VARCHAR(255) NOT NULL,
  TIPO VARCHAR(255) NOT NULL,
  CONSTRAINT PAR_REPORTS_PK PRIMARY KEY (id),
  CONSTRAINT PAR_REPORTS_FK1 FOREIGN KEY (sala_id)
  REFERENCES PAR_SALAS(ID) ON DELETE CASCADE
);

CREATE TABLE PAR_SALAS_USUARIOS
(
  ID SERIAL UNIQUE,
  USUARIO_ID INTEGER NOT NULL,
  SALA_ID INTEGER NOT NULL,
  CONSTRAINT PAR_SALAS_USUARIOS_PK PRIMARY KEY (ID),
  CONSTRAINT PAR_SALAS_USUARIOS_US_FK1 FOREIGN KEY (USUARIO_ID)
  REFERENCES PAR_USUARIOS (ID) ON DELETE CASCADE,
  CONSTRAINT PAR_SALAS_USUARIOS_CINES_FK1 FOREIGN KEY (SALA_ID)
  REFERENCES PAR_SALAS (ID) ON DELETE CASCADE
);

INSERT INTO par_version_bbdd (VERSION) VALUES ('2016-05-27.sql');