ALTER TABLE PAR_COMPRAS ADD COLUMN TIPO VARCHAR(250);

UPDATE PAR_COMPRAS SET TIPO='METALICO' WHERE TAQUILLA IS TRUE AND REFERENCIA_PAGO IS NULL AND PAGADA IS TRUE;
UPDATE PAR_COMPRAS SET TIPO='TARJETAOFFLINE' WHERE TAQUILLA IS TRUE AND REFERENCIA_PAGO IS NOT NULL AND PAGADA IS TRUE;
UPDATE PAR_COMPRAS SET TIPO='TARJETA' WHERE TAQUILLA IS FALSE AND PAGADA IS TRUE;

INSERT INTO par_version_bbdd (VERSION) VALUES ('2016-11-02.SQL');