CREATE TABLE PAR_REPORTS
(
  ID SERIAL UNIQUE,
  SALA_ID INTEGER,
  CLASE VARCHAR(255) NOT NULL,
  TIPO VARCHAR(255) NOT NULL,
  CONSTRAINT PAR_REPORTS_PK PRIMARY KEY (id),
  CONSTRAINT PAR_REPORTS_FK1 FOREIGN KEY (sala_id)
  REFERENCES PAR_SALAS(ID) ON DELETE CASCADE
);

CREATE TABLE PAR_SALAS_USUARIOS
(
  ID SERIAL UNIQUE,
  USUARIO_ID INTEGER NOT NULL,
  SALA_ID INTEGER NOT NULL,
  CONSTRAINT PAR_SALAS_USUARIOS_PK PRIMARY KEY (ID),
  CONSTRAINT PAR_SALAS_USUARIOS_US_FK1 FOREIGN KEY (USUARIO_ID)
  REFERENCES PAR_USUARIOS (ID) ON DELETE CASCADE,
  CONSTRAINT PAR_SALAS_USUARIOS_CINES_FK1 FOREIGN KEY (SALA_ID)
  REFERENCES PAR_SALAS (ID) ON DELETE CASCADE
);

INSERT INTO par_version_bbdd (VERSION) VALUES ('2016-05-27.sql');

ALTER TABLE PAR_EVENTOS ADD COLUMN CINE_ID INTEGER NULL;

ALTER TABLE PAR_EVENTOS ADD CONSTRAINT PAR_EVENTOS_CINES_FK1 FOREIGN KEY (CINE_ID)
REFERENCES PAR_CINES(ID) ON DELETE CASCADE;

ALTER TABLE PAR_USUARIOS ADD COLUMN URL VARCHAR(255) NULL;

ALTER TABLE PAR_TARIFAS ADD COLUMN CINE_ID INTEGER NULL;

ALTER TABLE PAR_TARIFAS ADD CONSTRAINT PAR_TARIFAS_CINES_FK1 FOREIGN KEY (CINE_ID)
REFERENCES PAR_CINES(ID) ON DELETE CASCADE;

ALTER TABLE PAR_TIPOS_EVENTO ADD COLUMN CINE_ID INTEGER NULL;

ALTER TABLE PAR_TIPOS_EVENTO ADD CONSTRAINT PAR_TIPOS_EVENTO_CINES_FK1 FOREIGN KEY (CINE_ID)
REFERENCES PAR_CINES(ID) ON DELETE CASCADE;

ALTER TABLE PAR_SALAS ADD COLUMN ASIENTOS_NUMERADOS BOOLEAN DEFAULT TRUE;

INSERT INTO par_version_bbdd (VERSION) VALUES ('2016-06-14.SQL');

ALTER TABLE PAR_EVENTOS ADD COLUMN PROMOTOR VARCHAR(255) NULL;
ALTER TABLE PAR_EVENTOS ADD COLUMN NIF_PROMOTOR VARCHAR(255) NULL;

INSERT INTO par_version_bbdd (VERSION) VALUES ('2016-07-08.SQL');

ALTER TABLE PAR_EVENTOS ADD COLUMN IMAGEN_PUBLI OID;
ALTER TABLE PAR_EVENTOS ADD COLUMN IMAGEN_PUBLI_CONTENT_TYPE VARCHAR(255);
ALTER TABLE PAR_EVENTOS ADD COLUMN IMAGEN_PUBLI_SRC VARCHAR(255);

INSERT INTO par_version_bbdd (VERSION) VALUES ('2016-07-20.SQL');

ALTER TABLE PAR_CINES ADD COLUMN URL_PUBLIC VARCHAR(255);
ALTER TABLE PAR_CINES ADD COLUMN URL_PRIVACIDAD VARCHAR(255);
ALTER TABLE PAR_CINES ADD COLUMN URL_COMO_LLEGAR VARCHAR(255);
ALTER TABLE PAR_CINES ADD COLUMN MAIL_FROM VARCHAR(255);
ALTER TABLE PAR_CINES ADD COLUMN URL_PIE_ENTRADA VARCHAR(255);
ALTER TABLE PAR_CINES ADD COLUMN LOGO_REPORT VARCHAR(255);

ALTER TABLE PAR_MAILS ADD COLUMN URL_PUBLIC VARCHAR(255);
ALTER TABLE PAR_MAILS ADD COLUMN URL_PIE_ENTRADA VARCHAR(255);

CREATE TABLE PAR_TPVS_CINES
(
  ID SERIAL UNIQUE,
  TPV_ID INTEGER NOT NULL,
  CINE_ID INTEGER NOT NULL,
  CONSTRAINT PAR_TPVS_CINES_PK PRIMARY KEY (ID),
  CONSTRAINT PAR_TPVS_CINES_UQ UNIQUE (TPV_ID, CINE_ID),
  CONSTRAINT PAR_TPVS_CINES_TPV_FK FOREIGN KEY (TPV_ID)
  REFERENCES PAR_TPVS (ID) ON DELETE CASCADE,
  CONSTRAINT PAR_TPVS_CINES_CINE_FK FOREIGN KEY (CINE_ID)
  REFERENCES PAR_CINES (ID) ON DELETE CASCADE
);

ALTER TABLE PAR_TPVS DROP COLUMN default_tpv;

INSERT INTO par_version_bbdd (VERSION) VALUES ('2016-08-25.SQL');

ALTER TABLE PAR_CINES ADD COLUMN API_KEY VARCHAR(255);

INSERT INTO par_version_bbdd (VERSION) VALUES ('2016-09-09.SQL');

ALTER TABLE PAR_CINES ADD COLUMN BUTACASENTRADOENDISTINTOCOLOR BOOLEAN;
INSERT INTO par_version_bbdd (VERSION) VALUES ('2016-09-16.SQL');




UPDATE PAR_CINES
SET
  URL_PUBLIC      = 'https://entrades.almassora.es/par-public',
  URL_PRIVACIDAD  = 'http://www.almassora.es/es/page/politica-privacidad',
  URL_COMO_LLEGAR = 'http://example.com/documento.pdf',
  MAIL_FROM       = 'entrades@almassora.es',
  URL_PIE_ENTRADA = 'http://example.com/example.jpg',
  LOGO_REPORT     = 'logo-vertical-color.svg';

UPDATE PAR_MAILS
SET
  URL_PUBLIC      = 'https://entrades.almassora.es/par-public',
  URL_PIE_ENTRADA = 'http://example.com/example.jpg';

ALTER TABLE PAR_CINES ALTER COLUMN URL_PUBLIC SET NOT NULL;
ALTER TABLE PAR_CINES ALTER COLUMN URL_PRIVACIDAD SET NOT NULL;
ALTER TABLE PAR_CINES ALTER COLUMN URL_COMO_LLEGAR SET NOT NULL;
ALTER TABLE PAR_CINES ALTER COLUMN MAIL_FROM SET NOT NULL;
ALTER TABLE PAR_CINES ALTER COLUMN URL_PIE_ENTRADA SET NOT NULL;
ALTER TABLE PAR_CINES ALTER COLUMN LOGO_REPORT SET NOT NULL;
ALTER TABLE PAR_MAILS ALTER COLUMN URL_PUBLIC SET NOT NULL;
ALTER TABLE PAR_MAILS ALTER COLUMN URL_PIE_ENTRADA SET NOT NULL;

UPDATE PAR_CINES
SET
  API_KEY = 'kajshdka512hsdoiuqhiu654820';

UPDATE PAR_CINES
SET
  BUTACASENTRADOENDISTINTOCOLOR = FALSE;

UPDATE PAR_EVENTOS
SET CINE_ID = 1;
UPDATE PAR_TIPOS_EVENTO
SET CINE_ID = 1;

INSERT INTO PAR_REPORTS("id", sala_id, tipo, clase) values (1, 1, 'ENTRADATAQUILLA', 'es.uji.apps.par.report.EntradaTaquillaReport');
INSERT INTO PAR_REPORTS("id", sala_id, tipo, clase) values (2, 1, 'ENTRADAONLINE', 'es.uji.apps.par.report.EntradaReport');
INSERT INTO PAR_REPORTS("id", sala_id, tipo, clase) values (3, 1, 'pdfTaquilla', 'es.uji.apps.par.report.InformeTaquillaReport');
INSERT INTO PAR_REPORTS("id", sala_id, tipo, clase) values (4, 1, 'pdfEfectiu', 'es.uji.apps.par.report.InformeEfectivoReport');
INSERT INTO PAR_REPORTS("id", sala_id, tipo, clase) values (5, 1, 'pdfTpv', 'es.uji.apps.par.report.InformeTaquillaTpvSubtotalesReport');
INSERT INTO PAR_REPORTS("id", sala_id, tipo, clase) values (6, 1, 'pdfSGAE', 'es.uji.apps.par.report.InformeEventosReport');
INSERT INTO PAR_REPORTS("id", sala_id, tipo, clase) values (7, 1, 'pdfSesion', 'es.uji.apps.par.report.InformeSesionReport');

INSERT INTO PAR_USUARIOS (ID, NOMBRE, USUARIO, MAIL, URL) VALUES (1, 'Administració de l''ajuntament d''Almassora', 'admin', 'entrades@almassora.es', NULL);
INSERT INTO PAR_USUARIOS (ID, NOMBRE, USUARIO, MAIL, URL) VALUES (2, 'Eulen', 'eulen', 'mcvera@eulen.com', NULL);
INSERT INTO PAR_USUARIOS (ID, NOMBRE, USUARIO, MAIL, URL) VALUES (3, 'Gestió entrades Almassora', 'gestio', 'entrades@almassora.es', NULL);
INSERT INTO PAR_USUARIOS (ID, NOMBRE, USUARIO, MAIL, URL) VALUES (4, 'Public', 'public', 'entrades@almassora.es', 'entrades.almassora.es');

INSERT INTO PAR_SALAS_USUARIOS ("id", USUARIO_ID, SALA_ID) VALUES (1, 1, 1);
INSERT INTO PAR_SALAS_USUARIOS ("id", USUARIO_ID, SALA_ID) VALUES (2, 2, 1);
INSERT INTO PAR_SALAS_USUARIOS ("id", USUARIO_ID, SALA_ID) VALUES (3, 3, 1);
INSERT INTO PAR_SALAS_USUARIOS ("id", USUARIO_ID, SALA_ID) VALUES (4, 4, 1);