ALTER TABLE PAR_CINES ADD COLUMN URL_PUBLIC VARCHAR(255);
ALTER TABLE PAR_CINES ADD COLUMN URL_PRIVACIDAD VARCHAR(255);
ALTER TABLE PAR_CINES ADD COLUMN URL_COMO_LLEGAR VARCHAR(255);
ALTER TABLE PAR_CINES ADD COLUMN MAIL_FROM VARCHAR(255);
ALTER TABLE PAR_CINES ADD COLUMN URL_PIE_ENTRADA VARCHAR(255);
ALTER TABLE PAR_CINES ADD COLUMN LOGO_REPORT VARCHAR(255);

ALTER TABLE PAR_MAILS ADD COLUMN URL_PUBLIC VARCHAR(255) NOT NULL;
ALTER TABLE PAR_MAILS ADD COLUMN URL_PIE_ENTRADA VARCHAR(255) NOT NULL;

--Rellenar y hacer no nulas
--ALTER TABLE public.par_cines ALTER COLUMN URL_PUBLIC SET NOT NULL;
--ALTER TABLE public.par_cines ALTER COLUMN URL_PRIVACIDAD SET NOT NULL;
--ALTER TABLE public.par_cines ALTER COLUMN URL_COMO_LLEGAR SET NOT NULL;
--ALTER TABLE public.par_cines ALTER COLUMN MAIL_FROM SET NOT NULL;
--ALTER TABLE public.par_cines ALTER COLUMN LOGO_REPORT SET NOT NULL;
--ALTER TABLE public.par_mails ALTER COLUMN url_public SET NOT NULL;
--ALTER TABLE public.par_mails ALTER COLUMN url_pie_entrada SET NOT NULL;

CREATE TABLE PAR_TPVS_CINES
(
  ID SERIAL UNIQUE,
  TPV_ID INTEGER NOT NULL,
  CINE_ID INTEGER NOT NULL,
  CONSTRAINT PAR_TPVS_CINES_PK PRIMARY KEY (ID),
  CONSTRAINT PAR_TPVS_CINES_UQ UNIQUE (TPV_ID, CINE_ID),
  CONSTRAINT PAR_TPVS_CINES_TPV_FK FOREIGN KEY (TPV_ID)
  REFERENCES PAR_TPVS (ID) ON DELETE CASCADE,
  CONSTRAINT PAR_TPVS_CINES_CINE_FK FOREIGN KEY (CINE_ID)
  REFERENCES PAR_CINES (ID) ON DELETE CASCADE
);

ALTER TABLE PAR_TPVS DROP COLUMN default_tpv;

INSERT INTO par_version_bbdd (VERSION) VALUES ('2016-08-25.SQL');