ALTER TABLE PAR_CINES ADD COLUMN URL_PUBLIC VARCHAR(255);
ALTER TABLE PAR_CINES ADD COLUMN URL_PRIVACIDAD VARCHAR(255);
ALTER TABLE PAR_CINES ADD COLUMN URL_COMO_LLEGAR VARCHAR(255);
ALTER TABLE PAR_CINES ADD COLUMN MAIL_FROM VARCHAR(255);
ALTER TABLE PAR_CINES ADD COLUMN URL_PIE_ENTRADA VARCHAR(255);
ALTER TABLE PAR_CINES ADD COLUMN LOGO_REPORT VARCHAR(255);

ALTER TABLE PAR_MAILS ADD COLUMN URL_PUBLIC VARCHAR(255) NOT NULL;
ALTER TABLE PAR_MAILS ADD COLUMN URL_PIE_ENTRADA VARCHAR(255) NOT NULL;

--Rellenar y hacer no nulas
--ALTER TABLE PAR_CINES MODIFY URL_PUBLIC DEFAULT NULL NOT NULL;
--ALTER TABLE PAR_CINES MODIFY URL_PRIVACIDAD DEFAULT NULL NOT NULL;
--ALTER TABLE PAR_CINES MODIFY URL_COMO_LLEGAR DEFAULT NULL NOT NULL;
--ALTER TABLE PAR_CINES MODIFY MAIL_FROM DEFAULT NULL NOT NULL;
--ALTER TABLE PAR_CINES MODIFY URL_PIE_ENTRADA DEFAULT NULL NOT NULL;
--ALTER TABLE PAR_CINES MODIFY LOGO_REPORT DEFAULT NULL NOT NULL;
--ALTER TABLE PAR_MAILS MODIFY URL_PUBLIC DEFAULT NULL NOT NULL;
--ALTER TABLE PAR_MAILS MODIFY URL_PIE_ENTRADA DEFAULT NULL NOT NULL;


--Rellenar y hacer no nulas

INSERT INTO par_version_bbdd (VERSION) VALUES ('2016-08-25.SQL');