ALTER TABLE PAR_COMPRAS_BORRADAS ADD COLUMN PORCENTAJE_IVA REAL NULL;
ALTER TABLE PAR_COMPRAS_BORRADAS ADD COLUMN TIPO VARCHAR(250) NULL;
ALTER TABLE PAR_COMPRAS_BORRADAS ADD COLUMN ABONADO_ID integer NULL;

INSERT INTO par_version_bbdd (VERSION) VALUES ('2017-11-17.SQL');