-- DATOS EVENTOS

ALTER TABLE "PAR_EVENTOS" ADD (SUBTITULOS VARCHAR(400));

-- DATOS SESIONES

ALTER TABLE "PAR_SESIONES" ADD (VER_LING VARCHAR(400));
ALTER TABLE "PAR_SESIONES" ADD (RSS_ID VARCHAR(400));

-- TIPOS EVENTO

ALTER TABLE "PAR_TIPOS_EVENTO" ADD ("EXPORTAR_ICAA" NUMBER(1,0) DEFAULT 0);