-- DATOS EVENTOS

ALTER TABLE "PAR_EVENTOS" ADD (SUBTITULOS VARCHAR(400));

-- DATOS SESIONES

ALTER TABLE "PAR_SESIONES" ADD (VER_LING VARCHAR(400));
ALTER TABLE "PAR_SESIONES" ADD (RSS_ID VARCHAR(400));

-- TIPOS EVENTO

ALTER TABLE "PAR_TIPOS_EVENTO" ADD ("EXPORTAR_ICAA" NUMBER(1,0) DEFAULT 0);

-- ENVIOS

CREATE TABLE "PAR_ENVIOS"
(    
  "ID" NUMBER, 
  "FECHA_GENERACION_FICHERO" TIMESTAMP (6),
  "FECHA_ENVIO_FICHERO" TIMESTAMP (6)
);

ALTER TABLE "PAR_ENVIOS" ADD CONSTRAINT "PAR_ENVIOS_PK" PRIMARY KEY ("ID") ENABLE;
ALTER TABLE "PAR_ENVIOS" MODIFY ("ID" NOT NULL ENABLE);

-- ENVIOS SESIONES

CREATE TABLE "PAR_ENVIOS_SESIONES"
(
  "ID" NUMBER,
  "PAR_ENVIO_ID" integer,
  "PAR_SESION_ID" integer,
  "TIPO_ENVIO" VARCHAR(2)
 );
 
 ALTER TABLE "PAR_ENVIOS_SESIONES" ADD CONSTRAINT "PAR_ENVIOS_SESIONES_PK" PRIMARY KEY ("ID" ) ENABLE;
 ALTER TABLE "PAR_ENVIOS_SESIONES" MODIFY ("ID" NOT NULL ENABLE);
 ALTER TABLE "PAR_ENVIOS_SESIONES" MODIFY ("TIPO_ENVIO" NOT NULL ENABLE);
 
 ALTER TABLE "PAR_ENVIOS_SESIONES" ADD CONSTRAINT "PAR_ENVIOS_SESIONES_PAR_ENVIO_ID_fkey" FOREIGN KEY ("PAR_ENVIO_ID")
      REFERENCES "PAR_ENVIOS" ("ID") ON UPDATE CASCADE ON DELETE CASCADE ENABLE;
 ALTER TABLE "PAR_ENVIOS_SESIONES" ADD CONSTRAINT "PAR_ENVIOS_SESIONES_PAR_SESION_ID_fkey" FOREIGN KEY ("PAR_SESION_ID")
      REFERENCES "PAR_SESIONES" ("ID") ON UPDATE RESTRICT ON DELETE RESTRICT ENABLE;

