ALTER TABLE PAR_PRECIOS_PLANTILLA ADD ("AULA_TEATRO" NUMBER);
ALTER TABLE PAR_PRECIOS_SESION ADD ("AULA_TEATRO" NUMBER);

UPDATE PAR_PRECIOS_PLANTILLA SET AULA_TEATRO=0 WHERE AULA_TEATRO IS null;
UPDATE PAR_PRECIOS_SESION SET AULA_TEATRO=0 WHERE AULA_TEATRO IS null;