CREATE TABLE "PAR_CINES" 
(    
  "ID" NUMBER, 
  "CODIGO" VARCHAR2(6), 
  "NOMBRE" VARCHAR2(400), 
  "CIF" VARCHAR2(30), 
  "DIRECCION" VARCHAR2(500), 
  "COD_MUNICIPIO" VARCHAR2(400), 
  "NOM_MUNICIPIO" VARCHAR2(400), 
  "CP" VARCHAR2(400), 
  "EMPRESA" VARCHAR2(400), 
  "COD_REGISTRO" VARCHAR2(400), 
  "TFNO" VARCHAR2(400),
  "IVA" NUMBER 
);

ALTER TABLE "PAR_CINES" ADD CONSTRAINT "PAR_CINES_PK" PRIMARY KEY ("ID") ENABLE;
ALTER TABLE "PAR_CINES" MODIFY ("ID" NOT NULL ENABLE);

ALTER TABLE "PAR_CINES" MODIFY ("CODIGO" NOT NULL ENABLE);
ALTER TABLE "PAR_CINES" MODIFY ("NOMBRE" NOT NULL ENABLE);
ALTER TABLE "PAR_CINES" MODIFY ("CIF" NOT NULL ENABLE);
ALTER TABLE "PAR_CINES" MODIFY ("DIRECCION" NOT NULL ENABLE);
ALTER TABLE "PAR_CINES" MODIFY ("COD_MUNICIPIO" NOT NULL ENABLE);
ALTER TABLE "PAR_CINES" MODIFY ("NOM_MUNICIPIO" NOT NULL ENABLE);
ALTER TABLE "PAR_CINES" MODIFY ("CP" NOT NULL ENABLE);
ALTER TABLE "PAR_CINES" MODIFY ("EMPRESA" NOT NULL ENABLE);
ALTER TABLE "PAR_CINES" MODIFY ("COD_REGISTRO" NOT NULL ENABLE);
ALTER TABLE "PAR_CINES" MODIFY ("TFNO" NOT NULL ENABLE);
ALTER TABLE "PAR_CINES" MODIFY ("IVA" NOT NULL ENABLE);

CREATE TABLE "PAR_SALAS" 
(    
  "ID" NUMBER, 
  "CODIGO" VARCHAR2(6), 
  "NOMBRE" VARCHAR2(400), 
  "ASIENTOS" NUMBER, 
  "ASIENTO_DISC" NUMBER, 
  "ASIENTO_NORES" NUMBER, 
  "TIPO" VARCHAR2(30), 
  "FORMATO" VARCHAR2(500), 
  "SUBTITULO" VARCHAR2(400),
  "CINE_ID" NUMBER
);

ALTER TABLE "PAR_SALAS" ADD CONSTRAINT "PAR_SALAS_PK" PRIMARY KEY ("ID") ENABLE;
ALTER TABLE "PAR_SALAS" MODIFY ("ID" NOT NULL ENABLE);

ALTER TABLE "PAR_SALAS" MODIFY ("CODIGO" NOT NULL ENABLE);
ALTER TABLE "PAR_SALAS" MODIFY ("NOMBRE" NOT NULL ENABLE);
ALTER TABLE "PAR_SALAS" MODIFY ("ASIENTOS" NOT NULL ENABLE);
ALTER TABLE "PAR_SALAS" MODIFY ("ASIENTO_DISC" NOT NULL ENABLE);
ALTER TABLE "PAR_SALAS" MODIFY ("ASIENTO_NORES" NOT NULL ENABLE);
ALTER TABLE "PAR_SALAS" MODIFY ("TIPO" NOT NULL ENABLE);
ALTER TABLE "PAR_SALAS" MODIFY ("FORMATO" NOT NULL ENABLE);
ALTER TABLE "PAR_SALAS" MODIFY ("SUBTITULO" NOT NULL ENABLE);
ALTER TABLE "PAR_SALAS" MODIFY ("CINE_ID" NOT NULL ENABLE);

ALTER TABLE "PAR_SALAS" ADD CONSTRAINT "PAR_CINES_PAR_SALAS_FK1" FOREIGN KEY ("CINE_ID")
      REFERENCES "PAR_CINES" ("ID") ENABLE;

CREATE TABLE "PAR_PLANTAS_SALA" 
(    
  "ID" NUMBER, 
  "NOMBRE" VARCHAR2(400),
  "SALA_ID" NUMBER
);

ALTER TABLE "PAR_PLANTAS_SALA" ADD CONSTRAINT "PAR_PLANTAS_SALA_PK" PRIMARY KEY ("ID") ENABLE;
ALTER TABLE "PAR_PLANTAS_SALA" MODIFY ("ID" NOT NULL ENABLE);

ALTER TABLE "PAR_PLANTAS_SALA" MODIFY ("NOMBRE" NOT NULL ENABLE);
ALTER TABLE "PAR_PLANTAS_SALA" MODIFY ("SALA_ID" NOT NULL ENABLE);

ALTER TABLE "PAR_PLANTAS_SALA" ADD CONSTRAINT "PAR_PLANTAS_SALA_PAR_SALAS_FK1" FOREIGN KEY ("SALA_ID")
      REFERENCES "PAR_PLANTAS_SALA" ("ID") ENABLE;
      
-- DATOS PELICULAS

ALTER TABLE "PAR_EVENTOS" ADD ("EXPEDIENTE" VARCHAR(400));
ALTER TABLE "PAR_EVENTOS" ADD ("COD_DISTRI" VARCHAR(400));
ALTER TABLE "PAR_EVENTOS" ADD ("NOM_DISTRI" VARCHAR(400));
ALTER TABLE "PAR_EVENTOS" ADD ("NACIONALIDAD" VARCHAR(400));
ALTER TABLE "PAR_EVENTOS" ADD ("VO" VARCHAR(400));
ALTER TABLE "PAR_EVENTOS" ADD ("METRAJE" VARCHAR(400));

-- DATOS SESIONES

ALTER TABLE "PAR_SESIONES" ADD ("NOMBRE" VARCHAR(400));
ALTER TABLE "PAR_SESIONES" ADD ("SALA_ID" NUMBER);
ALTER TABLE "PAR_SESIONES" ADD ("FORMATO" VARCHAR(400));

ALTER TABLE "PAR_SESIONES" ADD CONSTRAINT "PAR_SESIONES_PAR_SALAS_FK1" FOREIGN KEY ("SALA_ID")
      REFERENCES "PAR_SALAS" ("ID") ENABLE;
