CREATE TABLE "PAR_ABONOS"
   (	"ID" NUMBER,
	"NOMBRE" VARCHAR2(255) NOT NULL,
	"PLANTILLA_ID" NUMBER NOT NULL,
	"ANULADO"	NUMBER(1,0),
	CONSTRAINT "PAR_ABONOS_PKEY" PRIMARY KEY ("ID"),
  CONSTRAINT "PAR_ABONOS_PAR_PLANTILLAS_FK1" FOREIGN KEY ("PLANTILLA_ID")
        REFERENCES "PAR_PLANTILLAS" ("ID") ENABLE
);

CREATE TABLE "PAR_SESIONES_ABONOS"
   (	"ID" NUMBER,
	    "SESION_ID" NUMBER NOT NULL,
	    "ABONO_ID" NUMBER NOT NULL,
	CONSTRAINT "PAR_SESIONES_ABONOS_PKEY" PRIMARY KEY ("ID"),
  CONSTRAINT "PAR_SES_ABONOS_SESIONES_FK1" FOREIGN KEY ("SESION_ID")
        REFERENCES "PAR_SESIONES" ("ID") ON DELETE CASCADE ENABLE,
  CONSTRAINT "PAR_SES_ABONOS_ABONOS_FK1" FOREIGN KEY ("ABONO_ID")
          REFERENCES "PAR_ABONOS" ("ID") ENABLE
);

CREATE TABLE "PAR_ABONADOS"
   (	"ID" NUMBER,
	    "ABONO_ID" NUMBER NOT NULL,
	    "NOMBRE" VARCHAR2(255 BYTE),
	    "APELLIDOS"	VARCHAR2(255 BYTE),
      "TFNO"	VARCHAR2(255 BYTE),
      "EMAIL"	VARCHAR2(255 BYTE),
      "FECHA"	TIMESTAMP(6),
      "IMPORTE"	NUMBER,
      "DIRECCION"	VARCHAR2(255 BYTE),
      "POBLACION"	VARCHAR2(255 BYTE),
      "CP"	VARCHAR2(255 BYTE),
      "PROVINCIA"	VARCHAR2(255 BYTE),
      "INFO_PERIODICA"	NUMBER(1,0),
      "ANULADO"	NUMBER(1,0),
      "ABONADOS"	VARCHAR2(3500 CHAR),
	CONSTRAINT "PAR_ABONADOS_PKEY" PRIMARY KEY ("ID"),
  CONSTRAINT "PAR_ABONADOS_ABONOS_FK1" FOREIGN KEY ("ABONO_ID")
        REFERENCES "PAR_ABONOS" ("ID") ENABLE
);

ALTER TABLE "PAR_COMPRAS" ADD (ABONADO_ID NUMBER);
ALTER TABLE "PAR_COMPRAS" ADD CONSTRAINT "PAR_COMPRAS_ABONADOS_FK1" FOREIGN KEY ("ABONADO_ID") REFERENCES "PAR_ABONADOS" ("ID") ENABLE;

INSERT INTO par_version_bbdd (VERSION) VALUES ('2014-12-17.SQL');