CREATE TABLE "PAR_EVENTOS_MULTISESION"
(
   "ID" NUMBER,
   "EVENTO_ID" NUMBER,
   "EVENTO_HIJO_ID" NUMBER
);

ALTER TABLE "PAR_EVENTOS_MULTISESION" ADD CONSTRAINT "PAR_EVENTOS_MULTISESION_PK" PRIMARY KEY ("ID") ENABLE;
ALTER TABLE "PAR_EVENTOS_MULTISESION" MODIFY ("EVENTO_ID" NOT NULL ENABLE);
ALTER TABLE "PAR_EVENTOS_MULTISESION" MODIFY ("EVENTO_HIJO_ID" NOT NULL ENABLE);
ALTER TABLE "PAR_EVENTOS_MULTISESION" ADD CONSTRAINT "PAR_EVENTOS_MULTISESION_FK1" FOREIGN KEY ("EVENTO_ID")
	  REFERENCES "PAR_EVENTOS" ("ID");
ALTER TABLE "PAR_EVENTOS_MULTISESION" ADD CONSTRAINT "PAR_EVENTOS_MULTISESION_FK2" FOREIGN KEY ("EVENTO_HIJO_ID")
	  REFERENCES "PAR_EVENTOS" ("ID");