ALTER TABLE PAR_CINES ADD (
"URL_PUBLIC" VARCHAR2(255),
"URL_PRIVACIDAD" VARCHAR2(255),
"URL_COMO_LLEGAR" VARCHAR2(255),
"MAIL_FROM" VARCHAR2(255),
"URL_PIE_ENTRADA" VARCHAR2(255),
"LOGO_REPORT" VARCHAR2(255)
);

ALTER TABLE PAR_MAILS ADD (
"URL_PUBLIC" VARCHAR2(255),
"URL_PIE_ENTRADA" VARCHAR2(255)
);

--Rellenar y hacer no nulas
--ALTER TABLE PAR_CINES MODIFY URL_PUBLIC DEFAULT NULL NOT NULL;
--ALTER TABLE PAR_CINES MODIFY URL_PRIVACIDAD DEFAULT NULL NOT NULL;
--ALTER TABLE PAR_CINES MODIFY URL_COMO_LLEGAR DEFAULT NULL NOT NULL;
--ALTER TABLE PAR_CINES MODIFY MAIL_FROM DEFAULT NULL NOT NULL;
--ALTER TABLE PAR_CINES MODIFY URL_PIE_ENTRADA DEFAULT NULL NOT NULL;
--ALTER TABLE PAR_CINES MODIFY LOGO_REPORT DEFAULT NULL NOT NULL;
--ALTER TABLE PAR_MAILS MODIFY URL_PUBLIC DEFAULT NULL NOT NULL;
--ALTER TABLE PAR_MAILS MODIFY URL_PIE_ENTRADA DEFAULT NULL NOT NULL;

INSERT INTO par_version_bbdd (VERSION) VALUES ('2016-08-25.SQL');