ALTER TABLE PAR_EVENTOS ADD (
CINE_ID NUMBER NULL
);

ALTER TABLE PAR_EVENTOS ADD CONSTRAINT PAR_EVENTOS_CINES_FK1 FOREIGN KEY (CINE_ID)
REFERENCES PAR_CINES (ID) ON DELETE CASCADE ENABLE;

ALTER TABLE PAR_USUARIOS ADD (
URL VARCHAR2(255) NOT NULL
);

ALTER TABLE PAR_TARIFAS ADD (
CINE_ID NUMBER NULL
);

ALTER TABLE PAR_TARIFAS ADD CONSTRAINT PAR_TARIFAS_CINES_FK1 FOREIGN KEY (CINE_ID)
REFERENCES PAR_CINES (ID) ON DELETE CASCADE ENABLE;


INSERT INTO par_version_bbdd (VERSION) VALUES ('2016-06-14.SQL');