ALTER TABLE PAR_CINES ADD (
"URL_PUBLIC" VARCHAR2(255)
);

ALTER TABLE PAR_MAILS ADD (
"URL_PUBLIC" VARCHAR2(255)
);

--Rellenar y hacer no nulas

INSERT INTO par_version_bbdd (VERSION) VALUES ('2016-08-25.SQL');