ALTER TABLE PAR_CINES ADD (
"URL_PUBLIC" VARCHAR2(255),
"URL_PRIVACIDAD" VARCHAR2(255),
"URL_COMO_LLEGAR" VARCHAR2(255),
"MAIL_FROM" VARCHAR2(255),
"URL_PIE_ENTRADA" VARCHAR2(255),
"LOGO_REPORT" VARCHAR2(255)
);

ALTER TABLE PAR_MAILS ADD (
"URL_PUBLIC" VARCHAR2(255),
"URL_PIE_ENTRADA" VARCHAR2(255)
);

--Rellenar y hacer no nulas
--ALTER TABLE PAR_CINES MODIFY URL_PUBLIC DEFAULT NULL NOT NULL;
--ALTER TABLE PAR_CINES MODIFY URL_PRIVACIDAD DEFAULT NULL NOT NULL;
--ALTER TABLE PAR_CINES MODIFY URL_COMO_LLEGAR DEFAULT NULL NOT NULL;
--ALTER TABLE PAR_CINES MODIFY MAIL_FROM DEFAULT NULL NOT NULL;
--ALTER TABLE PAR_CINES MODIFY URL_PIE_ENTRADA DEFAULT NULL NOT NULL;
--ALTER TABLE PAR_CINES MODIFY LOGO_REPORT DEFAULT NULL NOT NULL;
--ALTER TABLE PAR_MAILS MODIFY URL_PUBLIC DEFAULT NULL NOT NULL;
--ALTER TABLE PAR_MAILS MODIFY URL_PIE_ENTRADA DEFAULT NULL NOT NULL;

CREATE TABLE PAR_TPVS_CINES (
  id      INTEGER NOT NULL,
  tpv_id  INTEGER NOT NULL,
  cine_id INTEGER NOT NULL,
  CONSTRAINT "PAR_TPVS_CINES_PK" PRIMARY KEY (id),
  CONSTRAINT "PAR_TPVS_CINES_UQ" UNIQUE (tpv_id, cine_id),
  CONSTRAINT "PAR_TPVS_CINES_TPV_FK" FOREIGN KEY (tpv_id)
  REFERENCES PAR_TPVS ("ID") ON DELETE CASCADE ENABLE,
  CONSTRAINT "PAR_TPVS_CINES_CINE_FK" FOREIGN KEY (cine_id)
  REFERENCES PAR_CINES ("ID") ON DELETE CASCADE ENABLE
);

ALTER TABLE  PAR_TPVS DROP COLUMN default_tpv;

INSERT INTO par_version_bbdd (VERSION) VALUES ('2016-08-25.SQL');