ALTER TABLE PAR_COMPRAS ADD (TIPO VARCHAR(250));

UPDATE PAR_COMPRAS SET TIPO='METALICO' WHERE TAQUILLA=1 AND REFERENCIA_PAGO IS NULL AND PAGADA = 1;
UPDATE PAR_COMPRAS SET TIPO='TARJETAOFFLINE' WHERE TAQUILLA=1 AND REFERENCIA_PAGO IS NOT NULL AND PAGADA = 1;
UPDATE PAR_COMPRAS SET TIPO='TARJETA' WHERE TAQUILLA=0 AND PAGADA = 1;

INSERT INTO par_version_bbdd (VERSION) VALUES ('2016-11-02.SQL');