ALTER TABLE PAR_COMPRAS_BORRADAS ADD (PORCENTAJE_IVA NUMBER NULL);
ALTER TABLE PAR_COMPRAS_BORRADAS ADD (TIPO VARCHAR(250) NULL);
ALTER TABLE PAR_COMPRAS_BORRADAS ADD (ABONADO_ID NUMBER NULL);

INSERT INTO par_version_bbdd (VERSION) VALUES ('2017-11-17.SQL');